services:
  # Backend API Service
  - type: web
    name: finance-sentiment-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: USE_LIGHTWEIGHT_SENTIMENT
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: finance_sentiment
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: FRONTEND_URL
        value: https://finance-sentiment-app-1.onrender.com
    healthCheckPath: /
    
  # Frontend Service (Static Site)
  - type: web
    name: finance-sentiment-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: finance-sentiment-backend
          envVarKey: RENDER_EXTERNAL_URL
